# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56281e3d2442163b737acbb1c5b5116f4a82fd5087b156b1fdfccaeea18a78f216a7347f167d117fa1edc5c6edf512fb114cb420c703b3391ea6778f47e1966f

test:
  secret_key_base: 8cb87cd73f48da5d59d76cefbd1fe10a63dfd29e50cfd12b371bc4ee0eaf5ea8ebb082c094cde568c82f930d5f2eb0d57911f7a7385c95b5ae19d57ffc200e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
